[package]
name = "support-logs"
version = "0.0.0"
authors = ["Matt Briggs <brigmatt@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2018"
publish = false

[dependencies]
snafu = "0.6"

[build-dependencies]
cargo-readme = "3.1"
